### ISSUE TITLE
Le joueur peut quitter une partie sans l'avoir fini ainsi le score n'est pas reset.

### ISSUE THREAD

**Issue by Thomas-Pollart** [cedric-duchemin/Unity-Space-Fighter#4]
## Informations générales
**Décrire le bug**
- Une description claire et concise de ce qu'est le bogue.

**Pour reproduire**
Étapes à suivre pour reproduire le comportement :
1. Lancez une partie.
2. Appuyez sur [Start/Enter] (le jeu devrait renvoyer au lobby)
3. Lancez une nouvelle partie.

**Comportement attendu**
- La partie devrait être mise en pause tant que le joueur n'a pas fini sa partie.

## **Captures d'écran**
None

## Suivi de la version
| Version | Réalisable|
| :-------: |  :---------: |
| 0.1.12 |✅|
| 0.1.13 |✅|

**Comment by cedric-duchemin** [comment]
### Issue corrigé
- Maintenant, quand le joueur appuiera sur Enter/Start la partie  sera mise en pause, autrement une fois la partie perdue le joueur sera renvoyé au menu principal.
